### ISSUE TITLE
WPS (Web Processing Service) Client - version 1.0.0

### ISSUE THREAD

**Issue by eblondel** [eblondel/ows4R#10]
- [x] WPS `1.0.0` GetCapabilities
- [x] WPS `1.0.0` DescribeProcess
- [x] WPS `1.0.0` Execute

**Comment by CedricMondy** [comment]
any progress about this feature?

**Comment by eblondel** [comment]
@CedricMondy that one is more on wishlist for the time being. I didn't get an opportunity & time to draft and release a client for WPS.
