### ISSUE TITLE
WFS query failing for reasons unknown

### ISSUE THREAD

**Issue by fdetsch** [eblondel/ows4R#129]
I am getting an error while querying [this WFS](https://www.wfs.nrw.de/geobasis/wfs_nw_inspire-flurstuecke_alkis?REQUEST=GetCapabilities&SERVICE=WFS) for German ALKIS parcel data. Here's my R code and the resulting error (that I cannot quite make sense of):

```r
wfs_r = ows4R::WFSClient$new(
  "https://www.wfs.nrw.de/geobasis/wfs_nw_inspire-flurstuecke_alkis"
  , serviceVersion = "2.0.0"
)

## get feature types and print to console
(
  feature_types = wfs_r$getFeatureTypes(
    pretty = TRUE
  )
)

## get features
wfs_r$getFeatures(
  feature_types$name[1L]
  , maxfeatures = 10L # not sure if this would be considered
)
```

> Error in startsWith(type, gml_xmlns$id) : non-character object(s)

By contrast, the code works in Python when querying the WFS through {owslib}:

```py
from owslib.wfs import WebFeatureService
import geopandas as gpd

wfs_py = WebFeatureService(
  'https://www.wfs.nrw.de/geobasis/wfs_nw_inspire-flurstuecke_alkis',
  version='2.0.0'
)

print(list(wfs_py.contents))

resp = wfs_py.getfeature(
  'cp:CadastralParcel',
  maxfeatures=10
)

result = gpd.read_file(resp)

result.shape # (10, 14)
type(result) # <class 'geopandas.geodataframe.GeoDataFrame'>
```

Any specific reason why the R {ows4R} based approach is failing?

**Comment by eblondel** [comment]
I will check ASAP and let you know

Le jeu. 28 nov. 2024, 15:29, Florian Detsch ***@***.***> a
écrit :

**Comment by eblondel** [comment]
just added a small patch that should make it work.

**Comment by fdetsch** [comment]
Confirmed, thanks!
