### ISSUE TITLE
Pass exact argument to findFeatureTypeByName() in getFeatures()?

### ISSUE THREAD

**Issue by maelle** [eblondel/ows4R#62]
https://github.com/eblondel/ows4R/blob/ad9d75210b8be81d998744fb944be48e7fd7b6b2/R/WFSClient.R#L95

Related to #56

**Comment by eblondel** [comment]
Actually, no we should not expect to pass exact parameter, in that case, implementing the OGC service the `getFeatures` should exactly match the feature type name. Same for other WxS services. exact should be always TRUE. If we would let user specify exact = FALSE, this would mean either to read features for 1st matched feature type name (as it is set now, wrongly), or let read everything which is not expected.
An OGC WFS `getFeatures` method should necessarily be done over a single coverage here. I will dig further into the standard to see if we can expect more than one type names, in which case this could be implemented and performing GetFeatures over multiple feature types.

**Comment by maelle** [comment]
Thank you :pray:
