### ISSUE TITLE
Implement progress bar in OWS data requests

### ISSUE THREAD

**Issue by eblondel** [eblondel/ows4R#73]

**Comment by eblondel** [comment]
@salvafern I just made some tests, it's easy to add httr::progress() but the issue is that we don't know a priori the size of the file requested, like WFS features or WCS coverage, which means the progress bar in % can't be added, the httr::progress() reports on the amount of data downloaded (file size). Not sure if it's what you need

**Comment by salvafern** [comment]
Ah ok I see. No, indeed this is not what I was thinking of, but if it is not much work could you add it anyways? That way we could know that the process is still alive when doing large requests.

**Comment by eblondel** [comment]
I've added it to GET requests for you to test. The issue with OGC services is that we are handling dynamic data services, where server doesn't communicate the size of the data requested. In this situation, `httr::progress` is not capable to configure a 0 to 100% progress bar, and can only update on the amount of data downloaded, which is not bad indeed, but not ideal... We can keep this open, and I'll dig a bit, at least in Geoserver, to see how far we can go.

**Comment by salvafern** [comment]
I have been testing and I think it is good to have the option, even if it is not an actual progress bar but just the bytes downloaded. Maybe keep it as an option? (e.g. when `logger = INFO`)

**Comment by eblondel** [comment]
sure no problem

**Comment by eblondel** [comment]
@salvafern it's implemented

**Comment by salvafern** [comment]
Great, thanks!!
