### ISSUE TITLE
Get all styles of a layer?

### ISSUE THREAD

**Issue by itati01** [eblondel/ows4R#74]
Hi,

I just started to play with ows4r, so I hope that I do not miss anything obvious. The goal is to get all styles belonging to a layer. I currently can get just one style:
```
wms <- WMSClient$new(wms_url, "1.3.0")
lyr <- wms$getCapabilities()$findLayerByName(layer_name)
lyr$getStyle()
```
Would it be possible to extend `getStyle` to get more/all styles (or with a new `getStyles` method)? Thanks!

**Comment by eblondel** [comment]
@itati01 it's a mistake, the right method should be `getStyles()`. Just pushed a fix, if you want you can test reinstalling ows4R from github.

**Comment by itati01** [comment]
@eblondel That was quick! Thanks a lot. By the way, is it possible to obtain attributes of the styles (e.g. title, names)?

**Comment by eblondel** [comment]
yes i can extend it, and replace the current method by 'getStylenames', i do a commit soon...

**Comment by itati01** [comment]
Thanks a lot. Both WMSLayer methods work. A small issue: the first two names in `getStylenames` are here identical.

**Comment by eblondel** [comment]
If you can send me the WMS you are trying to query. I suppose that the default style is listed as additional available style for the same layer you are looking at, it means that the style is referenced more than once in the WMS GetCapabilities. I've tested it over various WMS and it works fine.
