### ISSUE TITLE
Some pkgdown comments

### ISSUE THREAD

**Issue by maelle** [eblondel/ows4R#77]
Thanks for creating the pkgdown website! :pray: 

Suggestions
- Creating a pkgdown config (for instance via running `usethis::use_pkgdown()`) and add the website URL to it. It's better for cross-referencing from, say, EMODnetWFS docs. More info: https://pkgdown.r-lib.org/articles/linking.html?q=cross#across-packages
- Replacing the wiki link in the repo description with the website URL.
- Adding the pkgdown URL to DESCRIPTION https://github.com/eblondel/ows4R/blob/599fac8fdf07c23a55c8bdf6b02a3e7309d5b103/DESCRIPTION#L17
- Using Bootstrap 5 https://pkgdown.r-lib.org/articles/customise.html#getting-started (for instance the font size will be bigger)

**Comment by eblondel** [comment]
Thanks @maelle for the suggestions i'll have a look

**Comment by maelle** [comment]
:tada: :pray:
