### ISSUE TITLE
`summary$getDimensions()` not returning coefficients anymore

### ISSUE THREAD

**Issue by annakrystalli** [eblondel/ows4R#96]
See example below:

``` r
wcs <- ows4R::WCSClient$new(url = "https://geo.vliz.be/geoserver/Emodnetbio/wcs",
                            serviceVersion = "2.0.1")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> Loading IANA mime types...
#> No encoding supplied: defaulting to UTF-8.

summary <-  wcs$getCapabilities()$findCoverageSummaryById("Emodnetbio__cal_fin_19582016_L1_err",
                                                          exact = TRUE
)
summary$getDimensions()
#> Loading required package: sf
#> Linking to GEOS 3.10.2, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE
#> [[1]]
#> [[1]]$label
#> [1] "Lat"
#> 
#> [[1]]$uom
#> [1] "Deg"
#> 
#> [[1]]$type
#> [1] "geographic"
#> 
#> 
#> [[2]]
#> [[2]]$label
#> [1] "Long"
#> 
#> [[2]]$uom
#> [1] "Deg"
#> 
#> [[2]]$type
#> [1] "geographic"
#> 
#> 
#> [[3]]
#> [[3]]$label
#> [1] "time"
#> 
#> [[3]]$uom
#> [1] "s"
#> 
#> [[3]]$type
#> [1] "temporal"
```

<sup>Created on 2022-10-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Importantly, the [WCS vignette](https://eblondel.github.io/ows4R/articles/wcs.html#describe-a-coverage-describecoverage) still shows this method should work for getting coefficients

**Comment by eblondel** [comment]
I'll let you know, the fact we rely on proper binding from geometa, I see we miss GMLCOV Extension element managed in geometa. In the past this was managed through ows4R `WCSGSTimeDomain` clas but not anymore. I'm working on it

**Comment by eblondel** [comment]
Correction: it's supported, but we have an issue here again with the namespace loading approach

**Comment by eblondel** [comment]
@annakrystalli you should update geometa and ows4R , next test it again, this should work.

**Comment by annakrystalli** [comment]
Great! Could you bump the version so I can pin it as a minimum version in EMODnetWCS?

**Comment by eblondel** [comment]
pending rev is 0.3-2 on github (0.3-1 on CRAN). I don't use extended 900x dev rev numbers, but update pkg date, but I can increment dev versions if you think it's needed. 
I'm also moving some pkgs that are set in depends to Imports, and i've put a min version of geometa (--> the one on Github).
I hope to publish soon geometa on CRAN, afterwhat i will be able to push the current ows4R revision in CRAN as well.
